# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_uid', models.IntegerField()),
                ('m_gid', models.IntegerField()),
                ('m_goods_num', models.IntegerField()),
                ('m_time', models.DateTimeField(auto_now_add=True)),
                ('m_order_num', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'myorder',
            },
        ),
    ]
