# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='m_ispay',
            field=models.BooleanField(default=False),
        ),
    ]
